# Generated by Django 3.1 on 2020-08-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('id_school', models.IntegerField()),
                ('id_grade', models.IntegerField()),
                ('id_tutor', models.IntegerField()),
                ('log_code', models.CharField(max_length=50)),
            ],
        ),
    ]
