# Generated by Django 3.1 on 2020-08-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='id_grade',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='id_school',
            new_name='school',
        )
    ]
